[package]
name          = "mews"
version       = "0.1.0"
edition       = "2021"
authors       = ["kanarus <kanarus786@gmail.com>"]
documentation = "https://docs.rs/mews"
homepage      = "https://crates.io/crates/mews"
repository    = "https://github.com/ohkami-rs/mews"
readme        = "README.md"
license       = "MIT"
description   = "minimal and efficient, multiple-environment WebSocket implementation"
keywords      = ["websocket"]
categories    = ["web-programming"]

[dependencies]
tokio         = { version = "1",   optional = true, features = ["net"] }
async-std     = { version = "1",   optional = true }
smol          = { version = "2",   optional = true }
glommio       = { version = "0.9", optional = true }
futures-util  = { version = "0.3", optional = true, default-features = false, features = ["io"] }

[features]
tokio     = ["dep:tokio",     "tokio/io-util"   ]
async-std = ["dep:async-std"                    ]
smol      = ["dep:smol",      "dep:futures-util"]
glommio   = ["dep:glommio",   "dep:futures-util"]

### DEBUG ###
default = ["tokio"]