[package]
name          = "mews"
version       = "0.1.0"
edition       = "2021"
authors       = ["kanarus <kanarus786@gmail.com>"]
documentation = "https://docs.rs/mews"
homepage      = "https://crates.io/crates/mews"
repository    = "https://github.com/ohkami-rs/mews"
readme        = "README.md"
license       = "MIT"
description   = "minimal and efficient, multiple-environment WebSocket implementation"
keywords      = ["websocket"]
categories    = ["web-programming"]

[dependencies]
tokio         = { optional = true, version = "1", features = ["net", "io-util"] }
async-std     = { optional = true, version = "1"   }
smol          = { optional = true, version = "2"   }
glommio       = { optional = true, version = "0.9" }
futures-util  = { optional = true, version = "0.3", default-features = false, features = ["io"] }

sha1          = { version = "0.10", default-features = false }
base64        = { version = "0.22" }

[features]
tokio     = ["dep:tokio"]
async-std = ["dep:async-std"]
smol      = ["dep:smol"]
glommio   = ["dep:glommio",  "dep:futures-util"]

### DEBUG ###
default = ["tokio"]