version: '3'

tasks:
  CI:
    deps:
      - tokio
      - async-std
      - smol
      - glommio

  tokio:
    cmds:
      - cargo test --doc --features tokio
      - cargo test --lib --features tokio
  async-std:
    cmds:
      - cargo test --doc --features async-std
      - cargo test --lib --features async-std
  smol:
    cmds:
      - cargo test --doc --features smol
      - cargo test --lib --features smol
  glommio:
    cmds:
      - cargo test --doc --features glommio
      - cargo test --lib --features glommio
