version: 3

tasks:
  CI:
    deps:
      - for:  [tokio, async-std, smol, glommio]
        task: test:rt
        vars: { rt: '{{.ITEM}}' }
      - task: test:doc
      - task: check:no_runtime

  test:rt:
    cmds:
      - cargo test --lib --features {{.rt}}

  test:doc:
    cmds:
      - cargo test --doc --features tokio,DEBUG

  check:no_runtime:
    cmds:
      - cargo check
