version: 3

tasks:
  CI:
    deps:
      - for:  [tokio, async-std, smol, glommio]
        task: test:rt
        vars: { rt: '{{.ITEM}}' }
      - task: test:no_rt
      - task: test:doc

  test:rt:
    cmds:
      - cargo test --lib --features {{.rt}}

  test:no_rt:
    cmds:
      - cargo test

  test:doc:
    cmds:
      - cargo test --doc --features tokio,DEBUG
