version: '3'

tasks:
  CI:
    deps:
      - test:tokio
      - test:async-std
      - test:smol
      - test:glommio
      - test:doc

  test:tokio:
    cmds:
      - cargo test --lib --features tokio
  test:async-std:
    cmds:
      - cargo test --lib --features async-std
  test:smol:
    cmds:
      - cargo test --lib --features smol
  test:glommio:
    cmds:
      - cargo test --lib --features glommio
  test:doc:
    cmds:
      - cargo test --doc --features tokio
